### ISSUE TITLE
Download stuck for long list of songs

### ISSUE THREAD

**Issue by GrayGalaxy** [GrayGalaxy/jiosaavn-downloader#7]
As @jineshpatel30 mentioned in [this issue](https://github.com/GrayGalaxy/jiosaavn-downloader/issues/5#issuecomment-840625331) when downloading a large playlist few of the songs doesn't get downloaded and the whole operation gets stuck.

**Comment by GrayGalaxy** [comment]
I am closing this issue as it is fixed in 572fa4db10bb4d0fc1872a35e180efe9517dce03

**Comment by jineshpatel30** [comment]
@GrayGalaxy for some reason download is still getting stuck. No errors available. May be you can add a wait time after which it skip the stuck songs and create a zip of already downloaded songs?

https://www.jiosaavn.com/s/playlist/0f8d02afa160d2ea7d9ef4bedf677fd9/Mixed/WCRk5cjKO3lFo9wdEAzFBA__

**Comment by GrayGalaxy** [comment]
@jineshpatel30 I solved this issue on alpha channel in e781a74dd2641bbbcd2118e7ef75ac34b0dfdc2e. Now the quality automatically changes accordingly to your preferred bitrate if it is unavailable.

**Comment by jineshpatel30** [comment]
> @jineshpatel30 I solved this issue on alpha channel in [e781a74](https://github.com/GrayGalaxy/jiosaavn-downloader/commit/e781a74dd2641bbbcd2118e7ef75ac34b0dfdc2e). Now the quality automatically changes accordingly to your preferred bitrate if it is unavailable.

Great, I see some other interesting changes as well. Looking forward to trying new version!
